### ISSUE TITLE
[Blindscan] import error - No module named 'filters'

### ISSUE THREAD

**Issue by nickersk** [oe-alliance/oe-alliance-plugins#382]
https://github.com/oe-alliance/oe-alliance-plugins/blob/e535a8f0132275c7e6e6f5238756e073627a1fba/Blindscan/src/plugin.py#L32

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/PluginComponent.py", line 56, in readPluginList
    plugin = my_import('.'.join(["Plugins", c, pluginname, "plugin"]))
  File "/usr/lib/enigma2/python/Tools/Import.py", line 2, in my_import
    mod = __import__(name)
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/Blindscan/plugin.py", line 32, in <module>
    from filters import TransponderFiltering # imported from Blindscan folder
ModuleNotFoundError: No module named 'filters'

**Comment by nickersk** [comment]
fixed here: https://github.com/oe-alliance/oe-alliance-plugins/commit/2b27a69559ee38352f3174d6eed79de4086a2951
