### ISSUE TITLE
[tmdb] crash >  object has no attribute 'picload'

### ISSUE THREAD

**Issue by hd75hd** [oe-alliance/oe-alliance-plugins#744]
If you are in the seasons or in the cast and navigate there too quickly, in my example a long way down, then it crashes sporadically.

I can reproduce the crash in openATV and openVix

```
2023-08-12 18:17:58.1247 [ePicLoad] decode picture... /var/volatile/tmp/tmdb/130640.jpg
2023-08-12 18:17:58.1323 [gRC] Warning: Main thread is busy, displaying spinner!
2023-08-12 18:17:58.1796 [gAccel] accel alloc failed

2023-08-12 18:17:58.1797 [gSurface] ERROR: accelAlloc failed
2023-08-12 18:17:58.1845 [eRCDeviceInputDev] 2 6c 1
2023-08-12 18:17:58.1858 [ePicLoad] setPara max-X=480 max-Y=720 aspect_ratio=1,000000 cache=0 resize=1 bg=#00000000
2023-08-12 18:17:58.1860 [ePicLoad] decode picture... /var/volatile/tmp/tmdb/224235.jpg
2023-08-12 18:17:58.2948 [InfoBarGenerics] Key 'KEY_DOWN' (108) Repeat.
2023-08-12 18:17:58.2951 [ActionMap] Map context 'TMDbActions' -> Action 'down'.
2023-08-12 18:17:58.2957 [ePicLoad] - Weird situation, I wasn't decoding anything!
2023-08-12 18:17:58.2967 Traceback (most recent call last):
2023-08-12 18:17:58.2968   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 276, in action
2023-08-12 18:17:58.2972   File "/usr/lib/enigma2/python/Plugins/Extensions/tmdb/tmdb.py", line 1069, in keyDown
2023-08-12 18:17:58.2975   File "/usr/lib/enigma2/python/Plugins/Extensions/tmdb/tmdb.py", line 1006, in getInfo
2023-08-12 18:17:58.2977   File "/usr/lib/enigma2/python/Plugins/Extensions/tmdb/tmdb.py", line 1022, in showCover
2023-08-12 18:17:58.2984 AttributeError: 'tmdbScreenPeople' object has no attribute 'picload'
2023-08-12 18:17:58.2985 [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.HelpableActionMap object at 0xaf8214d0>>,('TMDbActions', 'down')) failed)
```

```2023-08-12 18:20:38.0655 [gAccel] accel alloc failed

2023-08-12 18:20:38.0656 [gSurface] ERROR: accelAlloc failed
2023-08-12 18:20:38.0724 Exception ignored in thread started by: <function threadDownloadPage at 0xafcf33e8>
2023-08-12 18:20:38.0725 Traceback (most recent call last):
2023-08-12 18:20:38.0726   File "/usr/lib/enigma2/python/Plugins/Extensions/tmdb/tmdb.py", line 111, in threadDownloadPage
2023-08-12 18:20:38.0735   File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 10, in __call__
2023-08-12 18:20:38.0746   File "/usr/lib/enigma2/python/Plugins/Extensions/tmdb/tmdb.py", line 1367, in getData
2023-08-12 18:20:38.0760 Traceback (most recent call last):
2023-08-12 18:20:38.0761   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 276, in action
2023-08-12 18:20:38.0774   File "/usr/lib/enigma2/python/Plugins/Extensions/tmdb/tmdb.py", line 1424, in keyDown
2023-08-12 18:20:38.0834   File "/usr/lib/enigma2/python/Plugins/Extensions/tmdb/tmdb.py", line 1364, in getInfo
2023-08-12 18:20:38.0861 [ePicLoad] setPara max-X=480 max-Y=360 aspect_ratio=1,000000 cache=0 resize=1 bg=#00000000
2023-08-12 18:20:38.0864 [ePicLoad] decode picture... /var/volatile/tmp/tmdb/2160908.jpg
2023-08-12 18:20:38.1406   File "/usr/lib/enigma2/python/Plugins/Extensions/tmdb/tmdb.py", line 1379, in showCover
2023-08-12 18:20:38.1409 [gAccel] accel alloc failed

2023-08-12 18:20:38.1410 [gSurface] ERROR: accelAlloc failed
2023-08-12 18:20:38.1445 AttributeError: 'tmdbScreenSeason' object has no attribute 'picload'
2023-08-12 18:20:38.1458   File "/usr/lib/enigma2/python/Plugins/Extensions/tmdb/tmdb.py", line 1379, in showCover
2023-08-12 18:20:38.1474 AttributeError: 'tmdbScreenSeason' object has no attribute 'picload'
2023-08-12 18:20:38.1476 [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.HelpableActionMap object at 0xaf90b9f0>>,('TMDbActions', 'down')) failed)```

**Comment by TwolDE2** [comment]
I will have a look, but if you can give me a script to follow would help

**Comment by TwolDE2** [comment]
By the way what box are you using …accel failed msg before crash

**Comment by TwolDE2** [comment]
It would be easier if you could raise the issue on https://www.world-of-satellite.com/ and then I can post an update for testing

**Comment by MrServo** [comment]
Just for info: **@hd75hd** have got an Testversion that will be committed when OK !

**Comment by hd75hd** [comment]
Fix with this commit

https://github.com/oe-alliance/oe-alliance-plugins/commit/f9a7aecace66d405ed0032aa151bb2383fb2bc0f

thanks @jbleyel
